server:
  servlet:
    session:
      timeout: PT24H
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000     #毫秒
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: on
logging:
  level:
    root: warn
    com.sunqi.blog: info
  file: log/blog-pro.log






